# author: Allan Ramos contato@allansrc.com.br>
name: time_elapsed
description: A package provides a easy way to get elapsed time from DateTime data
version: 0.3.0
homepage: https://github.com/allansrc/time_elapsed

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  pedantic: ^1.11.1
  test: ^1.25.5
