name: time_elapsed
description: A package provides a easy way to get elapsed time from DateTime data
version: 0.2.2+1
homepage: https://github.com/allansrc/time_elapsed

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: