name: time_elapsed
description: A package provides a easy way to get elapsed time from DateTime data
version: 0.2.4
homepage: https://github.com/allansrc/time_elapsed
# author: Allan Ramos <allanramos.teixeira@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0 